config/routes.rb
Rubyists::Application.routes.draw do
  resources :rubyists

   root :to => "rubyists#index"

end

app/models/rubyist.rb
class Rubyist < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rubyists_controller.rb
class RubyistsController < ApplicationController
  # GET /rubyists
  # GET /rubyists.xml
  def index
    @rubyists = Rubyist.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rubyists }
    end
  end

  # GET /rubyists/1
  # GET /rubyists/1.xml
  def show
    @rubyist = Rubyist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rubyist }
    end
  end

  # GET /rubyists/new
  # GET /rubyists/new.xml
  def new
    @rubyist = Rubyist.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rubyist }
    end
  end

  # GET /rubyists/1/edit
  def edit
    @rubyist = Rubyist.find(params[:id])
  end

  # POST /rubyists
  # POST /rubyists.xml
  def create
    @rubyist = Rubyist.new(params[:rubyist])

    respond_to do |format|
      if @rubyist.save
        format.html { redirect_to(@rubyist, :notice => 'Rubyist was successfully created.') }
        format.xml  { render :xml => @rubyist, :status => :created, :location => @rubyist }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rubyist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rubyists/1
  # PUT /rubyists/1.xml
  def update
    @rubyist = Rubyist.find(params[:id])

    respond_to do |format|
      if @rubyist.update_attributes(params[:rubyist])
        format.html { redirect_to(@rubyist, :notice => 'Rubyist was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rubyist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rubyists/1
  # DELETE /rubyists/1.xml
  def destroy
    @rubyist = Rubyist.find(params[:id])
    @rubyist.destroy

    respond_to do |format|
      format.html { redirect_to(rubyists_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rubyists_helper.rb
module RubyistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <body>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
<title>The Rubyists</title>
</head>
<head>
  <title>Rubyists</title>
  <%= stylesheet_link_tag 'style' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
<title>The Rubyists</title>
<link rel="stylesheet" type="text/css" href="style.css" />
</head>
<body>

<div id="main_container">

	<div id="header">
    <div class="logo">
   

    </div>

    </div>




    <div id="main_content">

    	<div class="center_content">

            <div id="menu_tab">
                    <ul class="menu">
                         <li><%=link_to 'Home',rubyists_path, :class=> 'nav_selected' %></li>
                         <li><%=link_to 'Rubyists',rubyists_path, :class=> 'nav' %></li>
                    </ul>
            </div>



            <div class="welcome_block">
            	

                     <div class="prod_box">

                    	
                        <div class="welcome_details">


<%= yield %>
                    </div>


            </div>


            <div class="products">
            
            </div>


            <div class="new_products">
            		

                    <div class="prod_box">

                    	
                    </div>


                    <div class="prod_box">
                    	

                        <div class="prod_details">
                        	
                        </div>
                    </div>


            		<div class="clear"></div>
            </div>




        </div>


    </div>

    <div id="footer">
        
    </div>

</div>
</body>
</html>

app/views/rubyists/_form.html.erb
<%= form_for(@rubyist) do |f| %>
  <% if @rubyist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rubyist.errors.count, "error") %> prohibited this rubyist from being saved:</h2>

      <ul>
      <% @rubyist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :experience %><br />
    <%= f.text_field :experience %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :cols =>60, :rows => 6%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rubyists/edit.html.erb
<h1>Editing rubyist</h1>

<%= render 'form' %>

<%= link_to 'Show', @rubyist %> |
<%= link_to 'Back', rubyists_path %>

app/views/rubyists/index.html.erb
<h1>All Rubyists</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Experience</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rubyists.each do |rubyist| %>
  <tr>
    <td><%= rubyist.name %></td>
    <td><%= rubyist.experience %></td>
    <td><%= rubyist.description %></td>
    <td><%= link_to 'Show', rubyist %></td>
    <td><%= link_to 'Edit', edit_rubyist_path(rubyist) %></td>
    <td><%= link_to 'Destroy', rubyist, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rubyist', new_rubyist_path %>

app/views/rubyists/new.html.erb
<h1>New Rubyist</h1>

<%= render 'form' %>

<%= link_to 'Back', rubyists_path %>

app/views/rubyists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rubyist.name %>
</p>

<p>
  <b>Experience:</b>
  <%= @rubyist.experience %>
</p>

<p>
  <b>Description:</b>
  <%= @rubyist.description %>
</p>


<%= link_to 'Edit', edit_rubyist_path(@rubyist) %> |
<%= link_to 'Back', rubyists_path %>